language: csharp
solution: myapp.sln
env:
  global:
  - FRAMEWORK_NAME=aws-sdk-ios

before_install:
#- brew update
#- brew outdated carthage || brew upgrade carthage
#- pod repo update

#script: bash test.sh

stages:
  - deploy1
  - deploy2
 

jobs:
  include:
    - stage: deploy1
      script:
      - echo "test test" >> test.txt  
    - stage: deploy2
      script:
      - more test.txt   
       
      
# tags: true    
