language: csharp
solution: myapp.sln
env:
  global:
  - FRAMEWORK_NAME=aws-sdk-ios

before_install:
#- brew update
#- brew outdated carthage || brew upgrade carthage
#- pod repo update

script: bash test.sh

before_deploy:
- python  test.py deploy1
- python  test.py deploy2
- python  test.py deploy3
- python  test.py deploy4
- python  test.py deploy5
deploy:
#- provider: releases

- provider: script
  script: 
    - python  test.py test1
    - python  test.py test2
  
  on:
    repo: sunchunqiang/testapp

# tags: true    
