language: csharp
solution: myapp.sln
env:
  global:
  - FRAMEWORK_NAME=aws-sdk-ios

before_install:
#- brew update
#- brew outdated carthage || brew upgrade carthage
#- pod repo update

script: bash test.sh

stages:
  - deploy1
  - deploy2
  - deploy3
  - deploy4

jobs:
  include:
    - stage: deploy1
      script:python  test.py deploy1
    - stage: deploy2
      script:python  test.py deploy2    
    - stage: deploy3
      script:python  test.py deploy3
    - stage: deploy4
      script:python  test.py deploy4
# tags: true    
