language: csharp
solution: myapp.sln
env:
  global:
  - FRAMEWORK_NAME=aws-sdk-ios

before_install:
#- brew update
#- brew outdated carthage || brew upgrade carthage
#- pod repo update

#script: bash test.sh

stages:
  - deploy1
  - deploy2
 

jobs:
  include:
    - stage: deploy1
    before_deploy:
    - echo "dfdfddfdf" >> ttt.txt
    deploy:
    - provider: script
      script: 
        - more   ttt.txt
      on:
        repo: sunchunqiang/aws-sdk-ios
        tags: true 

    - stage: deploy2
    before_deploy:
    - echo "deploy2" >> deploy2.txt
    deploy:
    - provider: script
      script: 
        - more   deploy2.txt
      on:
        repo: sunchunqiang/aws-sdk-ios
        tags: true   
  
