language: csharp
solution: myapp.sln
env:
  global:
  - FRAMEWORK_NAME=aws-sdk-ios

before_install:
#- brew update
#- brew outdated carthage || brew upgrade carthage
#- pod repo update

#script: bash test.sh

stages:
  - deploy1
  - deploy2
  - deploy3
  - deploy4

jobs:
  include:
    - stage: deploy1
      script:
      - python  test.py deploy11
      on:
        repo: sunchunqiang/testapp
        tags: true    
    - stage: deploy2
      script:
      - python  test.py deploy12     
    - stage: deploy3
      script:
      - python  test.py deploy13    
    - stage: deploy4
      script:
      - python  test.py deploy14          
      
# tags: true    
